### ISSUE TITLE
run failed

### ISSUE THREAD

**Issue by KleinPan** [WisdomSky/Cloudflared-web#28]
2024-06-28T09:14:02.608650983Z  WebUI running on port 14333
2024-06-28T09:14:02.609138779Z  No pre-existing config file found.
2024-06-28T10:46:08.391266471Z  No pre-existing config file found.
2024-06-28T10:46:18.555410283Z  node:internal/deps/undici/undici:12618
2024-06-28T10:46:18.555576481Z      Error.captureStackTrace(err, this);
2024-06-28T10:46:18.555590289Z            ^
2024-06-28T10:46:18.555597818Z  
2024-06-28T10:46:18.555604297Z  TypeError: fetch failed
2024-06-28T10:46:18.555610782Z      at node:internal/deps/undici/undici:12618:11
2024-06-28T10:46:18.555617631Z      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-28T10:46:18.555624260Z      at async /var/app/backend/app.js:61:16 {
2024-06-28T10:46:18.555631199Z    cause: ConnectTimeoutError: Connect Timeout Error
2024-06-28T10:46:18.555637513Z        at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
2024-06-28T10:46:18.555643774Z        at node:internal/deps/undici/undici:7716:50
2024-06-28T10:46:18.555649977Z        at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)
2024-06-28T10:46:18.555656094Z        at process.processImmediate (node:internal/timers:476:21) {
2024-06-28T10:46:18.555662315Z      code: 'UND_ERR_CONNECT_TIMEOUT'
2024-06-28T10:46:18.555668441Z    }
2024-06-28T10:46:18.555674341Z  }
2024-06-28T10:46:18.555680188Z  
2024-06-28T10:46:18.555686123Z  Node.js v18.20.3
2024-06-28T10:48:10.384520728Z  WebUI running on port 14333
2024-06-28T10:48:10.393884186Z  No pre-existing config file found.
2024-06-28T10:48:17.244142709Z  No pre-existing config file found.
2024-06-28T10:48:27.364570188Z  node:internal/deps/undici/undici:12618
2024-06-28T10:48:27.364604009Z      Error.captureStackTrace(err, this);
2024-06-28T10:48:27.364609463Z            ^
2024-06-28T10:48:27.364613405Z  
2024-06-28T10:48:27.364617058Z  TypeError: fetch failed
2024-06-28T10:48:27.364620712Z      at node:internal/deps/undici/undici:12618:11
2024-06-28T10:48:27.364624712Z      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-28T10:48:27.364628692Z      at async /var/app/backend/app.js:61:16 {
2024-06-28T10:48:27.364632385Z    cause: ConnectTimeoutError: Connect Timeout Error
2024-06-28T10:48:27.364635843Z        at onConnectTimeout (node:internal/deps/undici/undici:7760:28)
2024-06-28T10:48:27.364639397Z        at node:internal/deps/undici/undici:7716:50
2024-06-28T10:48:27.364663936Z        at Immediate._onImmediate (node:internal/deps/undici/undici:7748:13)
2024-06-28T10:48:27.364669705Z        at process.processImmediate (node:internal/timers:476:21) {
2024-06-28T10:48:27.364673517Z      code: 'UND_ERR_CONNECT_TIMEOUT'
2024-06-28T10:48:27.364677264Z    }
2024-06-28T10:48:27.364680825Z  }
2024-06-28T10:48:27.364684283Z  
2024-06-28T10:48:27.364687671Z  Node.js v18.20.3

**Comment by WisdomSky** [comment]
Hello @KleinPan,

Based on the error logs you provided, it seems like there's a problem with your internet connection which prohibits it from connecting to https://registry.hub.docker.com.

This may also be caused by your DNS. Have you tried updating your DNS into 8.8.8.8 or 1.1.1.1?

**Comment by KleinPan** [comment]
ok，i will try,later repley

**Comment by KleinPan** [comment]
may be i am in china,it is not allowed to connect ?do you have any way help me ?

**Comment by Zoobdude** [comment]
Can you accsess this page? - [https://registry.hub.docker.com/v2/repositories/wisdomsky/cloudflared-web/tags/?page_size=100&page=1](https://registry.hub.docker.com/v2/repositories/wisdomsky/cloudflared-web/tags/?page_size=100&page=1)

**Comment by KleinPan** [comment]
no ,is it the reasion?

**Comment by WisdomSky** [comment]
Hi @KleinPan,

A fix for this has been added.  Currently the new image is being built and will be deployed after 20mins. 

You can try installing cloudflared-web again after 20mins using the `latest` or `2024.6.1` tag.

**Comment by WisdomSky** [comment]
@KleinPan an updated build has been deployed. please install the cloudflared-web docker image again using the `latest` or `2024.6.1` tag.

**Comment by KleinPan** [comment]
thank you,i will try later
